### ISSUE TITLE
Backups include backup folder

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#150]
I was wondering why each command was taking increasingly longer to run... the backups are saved in the builds folder, which is located in the final folder, so a new backup include all previous backups.

**Comment by evilfurryone** [comment]
Backups are usually stored in a separate folder and usually not inside the drupal folders. 

By default it's set to /var/backups and if the site is a multi-server then we usually store them in the /nfs-files/backups

So in this case the problem was just a configuration error and can be fixed by setting up new backup location.

**Comment by floretan** [comment]
Yes, this only affects local environments. The backup location wasn't changed, but what is considered as "drupal" did. The need for backups from local environments are really limited to the "oops, I didn't mean to do that" case. We could simply save the backups to /tmp, or simply skip backups for local environments.

**Comment by floretan** [comment]
Saving backups to /tmp causes some permission issues. I propose to just skip local backups. @tharna would that be ok with you?

**Comment by tharna** [comment]
Yes, I think local backups can be skipped.

**Comment by badrange** [comment]
+1 to skipping local backups - I have usually always turned those off because it makes the build and everything else slow for no good reason
